# Generated by Django 5.0.2 on 2024-02-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosyapp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
